name: Build check

on:
  push:
    branches:
      - sr/llvm-syscalls
  pull_request:
    branches:
      - main

jobs:
  x86_64:
    runs-on: [ self-hosted, NIX, X64]

    steps:
      - uses: actions/checkout@v3
      - name: nix build
        run: nix build
      
      - name: hello-world
        run: nix-shell -p gcc --run "./result/bin/txlat -I ./result/test/hello-world/hello-static-musl -O bin.out && ./bin.out 2> /dev/null"

  x86_64-cross-riscv64:
    runs-on: [ self-hosted, NIX, X64]

    steps:
      - uses: actions/checkout@v3
      - name: nix build
        run: nix build .#defaultPackage.riscv64-linux

  aarch64:
    runs-on: [ self-hosted, NIX, ARM64]

    steps:
      - uses: actions/checkout@v3
      - name: nix build
        run: nix build .#defaultPackage.aarch64-linux
      
      - name: hello-world
        run: nix-shell -p gcc --run "./result/bin/txlat -I ./result/test/hello-world/hello-static-musl -O bin.out && ./bin.out 2> /dev/null"
