name: Build check

on:
  push:
    branches:
      - sr/llvm-syscalls
  pull_request:
    branches:
      - main

jobs:
  build-x86_64:
    runs-on: [ self-hosted, NIX ]

    steps:
      - uses: actions/checkout@v3
      - name: nix build
        run: nix build

  build-x86_64-cross-riscv64:
    runs-on: [ self-hosted, X64_64 ]

    steps:
      - uses: actions/checkout@v3
      - name: nix build
        run: nix build .#defaultPackage.riscv64-linux
